name: Build SGX Node API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: Use Node.js ${{ matrix.node-version }}
      uses: papeloto/action-zip@v1
      with:
        files: ./
        dest: node-sgx.zip
        
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SW_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SW_SECRET_ACCESS_KEY }}
        aws-region: 'https://s3.fr-par.scw.cloud'

    - name: Copy Zip toScaleway Bucket 
      run: |
        aws s3 sync node-sgx.zip s3://ternoa/node_sgx/latest.zip

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync node-sgx.zip s3://ternoa/node_sgx/${{ github.sha }}.zip

